In [ ]:

import pandas as pd
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder

In [2]:
df= pd.read_csv('C:/Users/ASUS/Downloads/habibas/IpProject2/data/heart.csv')
df.info()
df.sample(6)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1024 non-null   float64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1023 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 112.2 KB

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
409,46,1,2,150,231,0,1.0,147,0,3.6,1,0,2,0
998,42,1,0,136,315,0,1.0,125,1,1.8,1,0,1,0
635,53,0,0,130,264,0,0.0,143,0,0.4,1,0,2,1
533,53,0,0,138,234,0,0.0,160,0,0.0,2,0,2,1
582,55,1,1,130,262,0,1.0,155,0,0.0,2,0,2,1
320,53,0,0,130,264,0,0.0,143,0,0.4,1,0,2,1

In [3]:
# Check for Missing Values
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     1
thalach     0
exang       0
oldpeak     2
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
# ── Check for Duplicate Rows
num_duplicates = df.duplicated().sum()
print(f'Number of duplicate rows: {num_duplicates}')

# Drop duplicate rows and keep the first occurrence
df.drop_duplicates(inplace=True)

# Confirm duplicates are removed
print(f'Duplicates after removal: {df.duplicated().sum()}')
print(f'Dataset shape after removing duplicates: {df.shape}')

Number of duplicate rows: 720
Duplicates after removal: 0
Dataset shape after removing duplicates: (305, 14)

In [ ]:

df.fillna({'restecg': df['restecg'].mode()[0]}, inplace=True)

df.fillna({'oldpeak':df['oldpeak'].mean()},inplace=True)

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:

scaler=MinMaxScaler()
df[['age', 'trestbps', 'chol', 'thalach','oldpeak']]=scaler.fit_transform(df[['age', 'trestbps', 'chol', 'thalach','oldpeak']])

In [ ]:

cols = ['sex', 'cp', 'fbs', 'exang', 'restecg', 'slope', 'ca', 'thal']
encoder = OneHotEncoder(sparse_output=False, drop='first')

encoded_array = encoder.fit_transform(df[cols])

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(cols),
    index=df.index
)

#
df = df.drop(columns=cols)
df = pd.concat([df, encoded_df], axis=1)

In [ ]:

corr=df.corr()['target']
print(corr)

age           -0.222436
trestbps      -0.143093
chol          -0.083355
thalach        0.419045
oldpeak       -0.430408
target         1.000000
sex_1         -0.284274
cp_1           0.247935
cp_2           0.314025
cp_3           0.073709
fbs_1         -0.034660
exang_1       -0.435867
restecg_1.0    0.174088
restecg_2.0   -0.067315
slope_1       -0.360740
slope_2        0.392221
ca_1          -0.234955
ca_2          -0.277773
ca_3          -0.207848
ca_4           0.048353
thal_1        -0.089255
thal_2         0.510987
thal_3        -0.477569
Name: target, dtype: float64

In [ ]:

cols = corr[abs(corr) < 0.1].index.tolist()

df = df.drop(columns=cols)

In [10]:
df.sample(10)

,age,trestbps,thalach,oldpeak,target,sex_1,cp_1,cp_2,exang_1,restecg_1.0,slope_1,slope_2,ca_1,ca_2,ca_3,thal_2,thal_3
167,0.583333,0.245283,0.702290,0.096774,1,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
274,0.770833,0.622642,0.511450,0.370968,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
521,0.604167,0.292453,0.557252,0.064516,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
159,0.250000,0.245283,0.847328,0.000000,1,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
270,0.291667,0.150943,0.687023,0.000000,1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
42,0.666667,0.339623,0.748092,0.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
74,0.395833,0.339623,0.603053,0.000000,0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
582,0.541667,0.339623,0.641221,0.000000,1,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
297,0.604167,0.528302,0.305344,0.129032,0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
216,0.750000,0.386792,0.427481,0.451613,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [ ]:

df.to_csv('C:/Users/ASUS/Downloads/habibas/IpProject2/data/cleaneddata.csv', index=False)